### ISSUE TITLE
操作文件可以增加utf8编码

### ISSUE THREAD

**Issue by FutureSenzhong** [long2ice/aerich#10]
我的模型py文件中有中文就会报错，希望可以支持，然后就是迁移默认值不生效，希望能支持

**Comment by FutureSenzhong** [comment]
默认值

**Comment by long2ice** [comment]
编码问题跟aerich没关系吧？默认值也是支持的

**Comment by FutureSenzhong** [comment]
不知道，我在报错的地方加了，encoding=“utf-8”就可以了

**Comment by long2ice** [comment]
已修复 https://github.com/long2ice/aerich/pull/11
