### ISSUE TITLE
@long2ice  Hello, regarding Module "\migrations\models\old_models" not found, I used your method above and still failed to solve my problem. Is there any other way to deal with it?

### ISSUE THREAD

**Issue by zhangyuxin123** [long2ice/aerich#22]
@long2ice  Hello, regarding Module "\migrations\models\old_models" not found, I used your method above and still failed to solve my problem. Is there any other way to deal with it? 
The following is the directory structure of my test project
[https://note.youdao.com/yws/api/personal/file/WEB10281d2a965db99ebbef67a0fe7874d2?method=download&shareKey=3ffe95da605e5e5ae8b22f2a1986a163](url)

_Originally posted by @zhangyuxin123 in https://github.com/long2ice/aerich/issues/14#issuecomment-655258837_

**Comment by long2ice** [comment]
Maybe `.\migrations\models\old_models`

**Comment by zhangyuxin123** [comment]
@long2ice Still suggest that the path cannot be found. Is it the reason of my project directory structure?

**Comment by long2ice** [comment]
Take a look your `aerich.ini`

**Comment by zhangyuxin123** [comment]
[aerich]
tortoise_orm = settings.ormconfig
location = .\migrations

**Comment by zhangyuxin123** [comment]
@long2ice  and ` location=./migrations`   not good

**Comment by long2ice** [comment]
1. delete directory `migrations` and `aerich.ini`
2. run `aerich init -t settings.ormconfig --location .\migrations`
3. run `aerich ini-db`

try it and take a look.

**Comment by zhangyuxin123** [comment]
Still not working, error code：`tortoise.exceptions.ConfigurationError: Module "\migrations\models\old_models" not found`

**Comment by zhangyuxin123** [comment]
My test project directory structure：
TestProject
  |--app1
      |--models
          |--models.py
          |--routers
  |--app1
      |--models
         |--models.py
      |--routers
  |--migrations
  |--aerich.ini
  |--main.py
  |--settings.py

**Comment by long2ice** [comment]
Why miss point there?

**Comment by zhangyuxin123** [comment]
My test project directory [structure：](https://note.youdao.com/yws/api/personal/file/WEB0dbdcb27cf38dc552c0c344d5f9213f0?method=download&shareKey=6db2fe4d48eca3b45e5bdc3c05a89d1f),
You can download to view

**Comment by zhangyuxin123** [comment]
My test project directory ： 
[Click to download pictures](https://note.youdao.com/yws/api/personal/file/WEB0dbdcb27cf38dc552c0c344d5f9213f0?method=download&shareKey=6db2fe4d48eca3b45e5bdc3c05a89d1f)
you can download to view

**Comment by zhangyuxin123** [comment]
@long2ice I don't know how to proceed

**Comment by long2ice** [comment]
是Windows还是Mac？

**Comment by zhangyuxin123** [comment]
windows

**Comment by long2ice** [comment]
目录migrations/models有吗

**Comment by zhangyuxin123** [comment]
有

**Comment by long2ice** [comment]
看你的截图好像没有

**Comment by zhangyuxin123** [comment]
有的，紧挨着app2目录的，我用的是vscode工具，在显示上他是这样显示的：migrations\models

**Comment by long2ice** [comment]
你从dev分支安装最新源码试试

**Comment by zhangyuxin123** [comment]
好的，我试试

**Comment by zhangyuxin123** [comment]
非常感谢，新版本(0.2.1)能迁移成功了

**Comment by zhangyuxin123** [comment]
另外，
如果是Mac，location是不是就要写成 ./migrations ?

**Comment by long2ice** [comment]
是的，我稍后更新一下pypi

**Comment by zhangyuxin123** [comment]
ok，十分感谢！
