### ISSUE TITLE
is Python version 3.7 possible?

### ISSUE THREAD

**Issue by maxim-s-barabash** [long2ice/aerich#25]
Hi. I want to test aerich but for now i am using python version 3.7

In new packages 0.2.1 you have a limited version of Python 3.8
Is it possible to return support for Python 3.7?

Now I installed the package with the command.
```
pip3.7  install  --ignore-requires-python aerich==0.2.1
```

**Comment by long2ice** [comment]
OK, you can install dev branch and git a try.

**Comment by maxim-s-barabash** [comment]
Thank. I will test :)

**Comment by SpyrosRoum** [comment]
So does this work with python 3.7 and if yes will it be official in the next release?
Doing 3.8 only is kinda limiting, I'd like to support at least 3.7 for my app and this is the last thing holding me back

**Comment by long2ice** [comment]
Yes for next release or just install from dev branch.
