### ISSUE TITLE
PostrgeSQL, aerich downgrade, OperationalError: syntax error at or near "FOREIGN"

### ISSUE THREAD

**Issue by maxim-s-barabash** [long2ice/aerich#27]
aerich v0.2.1

Hi. After executing the command `aerich downgrade` I get an error

OperationalError: syntax error at or near "FOREIGN"

cat 1_202059071720115939_user_companies.json

```json
{
...
  "downgrade": [
    "ALTER TABLE \"user\" DROP FOREIGN KEY \"fk_user_company_e03b12ac\"",
...
  ]
}
```

Changes to this variant and it worked
```json
{
...
  "downgrade": [
    "ALTER TABLE \"user\" DROP CONSTRAINT \"fk_user_company_e03b12ac\"",
...
  ]
}
```

**Comment by maxim-s-barabash** [comment]
@moubctez, cast

**Comment by long2ice** [comment]
Sorry I'm not so familiar with postgres syntax, this is fixed by https://github.com/long2ice/aerich/commit/2fcb2626fd51ac846f9525eb3106d47779a1312e, you can update from dev branch and try again.

**Comment by maxim-s-barabash** [comment]
It works for me. thank.
