### ISSUE TITLE
Datetime string is incorrect for migrate files.

### ISSUE THREAD

**Issue by SakuraSound** [long2ice/aerich#36]
You currently use 
https://github.com/long2ice/aerich/blob/e00eb7f3d9e312784b7ccee31bb1ee911f2359f1/aerich/migrate.py#L90

I believe you want to replace the first %M with %m and %D with %d,  per [strftime and strptime format codes](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes)

**Comment by long2ice** [comment]
Yes, you are right, thanks.
