### ISSUE TITLE
error setting up

### ISSUE THREAD

**Issue by gabbyprecious** [long2ice/aerich#39]
@long2ice I'm new to Tortoise ORM and aerich. I'm trying to use it with the FastAPI framework. Whenever I try setting up. I keep receiving this error:
```
Usage: aerich [OPTIONS] COMMAND [ARGS]...
Try "aerich -h" for help.

Error: No config named "tests.backends.mysql"
```

How do I set up them up together, the documentation so far isn't forthcoming

**Comment by long2ice** [comment]
Which command cause this error?

**Comment by gabbyprecious** [comment]
The command:
`$ aerich init-db`

I can't seem to set it up with postgres.

**Comment by long2ice** [comment]
run `aerich init` first

**Comment by gabbyprecious** [comment]
I did that. I have the aerich ini file and the migration folder

**Comment by long2ice** [comment]
`tests.backends.mysql` is your config? which should be dict point at.

**Comment by gabbyprecious** [comment]
![Screenshot from 2020-09-10 15-50-21](https://user-images.githubusercontent.com/47405251/92748803-6ccc2080-f37d-11ea-88fc-fcfc2028a5dc.png)
Here is how my config file and project look like.

**Comment by long2ice** [comment]
Then what's wrong run `aerich init-db`?

**Comment by gabbyprecious** [comment]
![Screenshot from 2020-09-10 15-54-48](https://user-images.githubusercontent.com/47405251/92749588-288d5000-f37e-11ea-9266-ae93dac58570.png)
Here is the error I keep getting.

**Comment by long2ice** [comment]
I know...You should rename `config.json` -> `config.py`

**Comment by gabbyprecious** [comment]
Still the same error. DO you have any project you've set up, I can use

**Comment by long2ice** [comment]
Maybe you should init with `aerich init -t config.TORTOISE_ORM` after delete old folder and file, please understand it instead of just copy example command.

**Comment by gabbyprecious** [comment]
Oh I get now. But the Json file is not been generated and it does timeout

**Comment by gabbyprecious** [comment]
Found my way around it. Thank you

**Comment by phacic** [comment]
@gabbyprecious  how exactly did you fix the issue. having the same thing here, naming conversion for the `-t` switch is correct

**Comment by phacic** [comment]
found a way around it. My config dict was in the app file so had to do this `aerich init -t app.TORTOISE_CONFIG` and this was throwing `no config found` error but moving the `TORTOISE_CONFIG` a `config.py`, `aerich init -t config.TORTOISE_CONFIG` worked. I don't really know why.
