### ISSUE TITLE
sqlite support?

### ISSUE THREAD

**Issue by mjhea0** [long2ice/aerich#40]
SQLite doesn't support `DROP COLUMN` columns:

```json
{
  "upgrade": [
    "ALTER TABLE \"foo\" ADD \"bar\" TEXT NOT NULL",
    "ALTER TABLE \"foo\" DROP COLUMN \"foo\""
  ],
  "downgrade": [
    "ALTER TABLE \"foo\" ADD \"foo\" TEXT NOT NULL",
    "ALTER TABLE \"foo\" DROP COLUMN \"bar\""
  ]
}
```

**Comment by long2ice** [comment]
I rarely used sqlite and know little about it's syntax, and wan't Intend to support it.

**Comment by mjhea0** [comment]
That's fine. Since Tortoise does support it, you may want to indicate on the README that SQLite isn't officially supported by Aerich to avoid confusion.

I tossed together a quick sample project for FastAPI + Tortoise + Aerich if you want to reference it: https://github.com/testdrivenio/fastapi-tortoise-aerich.

**Comment by pmdevita** [comment]
As of 3.35.0 https://sqlite.org/releaselog/3_35_0.html SQLite now supports DROP COLUMN. I did a very basic test where I commented out `def drop_column` in aerich/ddl/sqlite. This generated migrations with the command and I can confirm upgrade and downgrade work as expected.
