### ISSUE TITLE
Migrations are not created

### ISSUE THREAD

**Issue by alexeydad1** [long2ice/aerich#42]
Hello @long2ice !
I make changes to my models (add fields, rename, etc). After starting the migration, but in response I get:
**$ aerich migrate
No changes detected**
Everything was working and suddenly stopped, what could be the reason?

**Comment by long2ice** [comment]
run `init` and `init-db` before?

**Comment by alexeydad1** [comment]
Yes, I do, every time I launch the app.

**Comment by alexeydad1** [comment]
I wrote above that everything worked before
![image](https://user-images.githubusercontent.com/21141222/93109290-8db5ae00-f6bc-11ea-878c-27a38390d0e8.png)

**Comment by alexeydad1** [comment]
![image](https://user-images.githubusercontent.com/21141222/93118421-fa36aa00-f6c8-11ea-9bd9-340843ee5fa1.png)

**Comment by alexeydad1** [comment]
![image](https://user-images.githubusercontent.com/21141222/93118527-1c302c80-f6c9-11ea-9f65-f654349074c9.png)

**Comment by alexeydad1** [comment]
@long2ice My migrations started working. I tried to reproduce this error, but it didn't work.
I'm sorry to bother you.

**Comment by long2ice** [comment]
You are welcome.
