### ISSUE TITLE
Models.py is expected, having a models as a module causes issue

### ISSUE THREAD

**Issue by Vishnu-priyan** [long2ice/aerich#8]
So far aerich is good and thanks for your work on this. But i found that inside aerich/migrate.py  we are checking for models.py file,  line no 42 i think. And having a structure like so ,
```
models/
     __init__.py
    tables_1.py
    tables_2.py
```

Like the above is not working, what is the possible issue here? Am i missing something ? will this work, or do we need to keep all tables in one models.py for this to work.

**Comment by long2ice** [comment]
It should be worked as that, did you add both of those to tortoise_orm config? Just like:
```python
tortoise_orm = {
    "connections": {"default": expand_db_url(db_url, True)},
    "apps": {
        "models": {"models": ["models.tables_1","models.tables_2", "aerich.models"], "default_connection": "default",},
    },
}
```

**Comment by Vishnu-priyan** [comment]
Now aerich init is working, but when using migrate / upgrade issue occurs in tortoise's _discover_models , the following is occuring ModuleNotFoundError: No module named 'migrations.models.tables_1'

I will try to recreate this with a small  example and post it here, when possible.

**Comment by long2ice** [comment]
Did you install lastest version? Or you can reinstall from github: ``pip install -e git+https://github.com/long2ice/aerich.git@dev``
